# Generated by Django 3.2.6 on 2021-08-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_out1_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='datetime',
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
